--- #YAML:1.0
name:                Sub-ForceEval
version:             2.02
abstract:            eval subroutines, re-throw exceptions
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Attribute::Handlers:           0.78
    Carp:                          0
    strict:                        0
    Symbol:                        0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
